#!/usr/bin/env bash

cfg="git --git-dir=$HOME/.cfg --work-tree=$HOME"

$cfg pull

for filePath in $($cfg ls-files | grep ".asc$")
do
    decryptedFilePath=${filePath%.asc*}
    gpg -d $filePath > $decryptedFilePath
done
